dataset_name: "/home/shanghui/dsh/datasets/MVC/Wiki_fea.mat"
data_name : "Wiki_fea"
dataset_x_name: "X"
dataset_y_name: "Y"
drop_last : True

# hidden layer dimension
h_dim: 1024
z_dim : 128
gpu: "cuda"
seed: 2024
with_lowrank : True

lr : 0.000001

weight_decay : 0.0000001
epochs : 100
batch_size : 256
pretrain_epoch : 100