dataset_name: "/home/shanghui/dsh/datasets/MVC/COIL20.mat"
data_name : "COIL20"
dataset_x_name: "X"
dataset_y_name: "Y"
drop_last : True

# hidden layer dimension
h_dim: 1024
z_dim : 128
gpu: "cuda"
seed: 43
with_lowrank : True

lr : 0.0001
weight_decay : 0.0000001
epochs : 100
batch_size : 256
pretrain_epoch : 100
alph : 0.5